[package]
name = "teensy3-rs-demo"
version = "0.1.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>", "James Munns <james.munns@gmail.com>"]

[dependencies]
teensy3 = { path = "../teensy3-rs/teensy3" }
teensy3-sys = { path = "../teensy3-rs/teensy3-sys" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
